# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-09 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modify_datee',
            new_name='modify_date',
        ),
    ]
